import { Job, Applicant, User, DashboardStats } from './types';

export const mockUser: User = {
  id: '1',
  name: 'Steve Smith',
  email: 'steve@example.com',
  avatar: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=1',
  role: 'user',
  title: 'Senior Developer',
  skills: ['React', 'Node.js', 'TypeScript'],
  experience: '5+ years',
  location: 'Stockholm, Sweden',
};

export const mockRecruiter: User = {
  id: '2',
  name: 'John Recruiter',
  email: 'john@company.com',
  avatar: 'https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=1',
  role: 'recruiter',
  company: 'Tech Corp',
  title: 'Senior Recruiter',
};

export const mockApplicants: Applicant[] = [
  {
    id: '1',
    name: 'Jane Doe',
    email: 'jane@example.com',
    avatar: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=1',
    appliedDate: '2025-01-15',
    status: 'Hired',
    matchLevel: 95,
    skills: ['React', 'TypeScript', 'Node.js'],
    experience: '3+ years',
    location: 'Stockholm',
  },
  {
    id: '2',
    name: 'John Smith',
    email: 'john@example.com',
    avatar: 'https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=1',
    appliedDate: '2025-01-14',
    status: 'In Review',
    matchLevel: 87,
    skills: ['React', 'JavaScript', 'CSS'],
    experience: '2+ years',
    location: 'Stockholm',
  },
  {
    id: '3',
    name: 'Alice Johnson',
    email: 'alice@example.com',
    avatar: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=1',
    appliedDate: '2025-01-13',
    status: 'Interview',
    matchLevel: 92,
    skills: ['React', 'TypeScript', 'GraphQL'],
    experience: '4+ years',
    location: 'Stockholm',
  },
  {
    id: '4',
    name: 'Bob Wilson',
    email: 'bob@example.com',
    avatar: 'https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=1',
    appliedDate: '2025-01-12',
    status: 'Applied',
    matchLevel: 78,
    skills: ['React', 'JavaScript'],
    experience: '1+ years',
    location: 'Stockholm',
  },
];

export const mockJobs: Job[] = [
  {
    id: '1',
    title: 'Senior UI/UX Designer',
    company: 'Tech Corp',
    location: 'Stockholm, Sweden',
    type: 'Full-time',
    salary: '$80,000 - $120,000',
    description: 'We are looking for a talented Senior UI/UX Designer to join our growing team. You will be responsible for creating intuitive and engaging user experiences across our digital products.',
    requirements: [
      '5+ years of experience in UI/UX design',
      'Proficiency in Figma, Sketch, or Adobe Creative Suite',
      'Strong understanding of user-centered design principles',
      'Experience with responsive design and mobile-first approach',
      'Portfolio demonstrating successful design projects',
    ],
    benefits: [
      'Competitive salary and equity package',
      'Flexible working hours and remote work options',
      'Health, dental, and vision insurance',
      'Professional development budget',
      'Modern office with great team culture',
    ],
    datePosted: '2025-02-10',
    status: 'Open',
    applicants: mockApplicants,
    views: 120,
  },
  {
    id: '2',
    title: 'Frontend Developer',
    company: 'StartupXYZ',
    location: 'Stockholm, Sweden',
    type: 'Full-time',
    salary: '$70,000 - $100,000',
    description: 'Join our dynamic team as a Frontend Developer and help build the next generation of web applications using modern technologies.',
    requirements: [
      '3+ years of React development experience',
      'Strong knowledge of JavaScript/TypeScript',
      'Experience with modern CSS frameworks',
      'Understanding of RESTful APIs',
      'Git version control proficiency',
    ],
    benefits: [
      'Competitive salary',
      'Stock options',
      'Flexible schedule',
      'Learning budget',
      'Great team environment',
    ],
    datePosted: '2025-01-15',
    status: 'Open',
    applicants: mockApplicants.slice(0, 2),
    views: 85,
  },
  {
    id: '3',
    title: 'Product Manager',
    company: 'InnovateCorp',
    location: 'Stockholm, Sweden',
    type: 'Full-time',
    salary: '$90,000 - $130,000',
    description: 'We are seeking an experienced Product Manager to drive product strategy and execution for our flagship products.',
    requirements: [
      '4+ years of product management experience',
      'Strong analytical and problem-solving skills',
      'Experience with agile development methodologies',
      'Excellent communication and leadership skills',
      'Technical background preferred',
    ],
    benefits: [
      'Competitive compensation',
      'Equity participation',
      'Comprehensive benefits',
      'Professional growth opportunities',
      'Collaborative work environment',
    ],
    datePosted: '2024-12-20',
    status: 'Closed',
    applicants: mockApplicants.slice(0, 3),
    views: 200,
  },
];

export const mockDashboardStats: DashboardStats = {
  applications: 1200,
  views: 200,
  hired: 300,
  rejected: 450,
};